version: "3.8"
name: go-auth

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "go-auth"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: